name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/setup-helm@v1
      - name: Install Helm plugins
        run: |
          helm plugin install https://github.com/instrumenta/helm-kubeval 
          helm plugin install https://github.com/instrumenta/helm-conftest

      - name: Helm lint
        run: helm lint .

      - name: Kubeval
        run: helm kubeval .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.14.6" # The Go version to download (if necessary) and use.

      - uses: azure/setup-helm@v1

#      - uses: azure/setup-kubectl@v1

#      - name: Create k8s Kind Cluster
#        uses: helm/kind-action@v1.0.0

#      - uses: actions/checkout@v2

#      - name: Install Test dependencies
#        run: cd test && go mod download

  release:
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @brpaz/semantic-release-helm
        env:
          GITHUB_TOKEN: "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"
